#!/usr/bin/env sh
#
# Verify that every signal connection wired in a scene resolves to a method that
# actually exists.
#
# This is the one Godot failure mode no C# analyzer can see. A connection lives
# in the .tscn as plain text:
#
#   [connection signal="pressed" from="Button" to="." method="OnPressed"]
#
# Rename or delete OnPressed and the project still compiles, `make lint` still
# passes, and the game fails at runtime the first time the signal fires - often
# in a scene nobody loads during testing. Roslyn cannot read scene files, so
# nothing else in this bundle covers it.
#
#   ./check-signals.sh [path]     # defaults to the current directory
#
# Exits non-zero when a connection points at a method that does not exist.
#
# Scope, deliberately: this checks that the method exists *somewhere* in the
# project, not that it exists on the class attached to the target node.
# Resolving `to="../Foo/Bar"` to a script means walking the node tree and the
# ext_resource table, which is a parser rather than a grep. The loose check
# already catches the common failure - a handler renamed or deleted while the
# connection stayed behind - without any false positives from node paths.

set -eu

ROOT="${1:-.}"

if [ ! -d "$ROOT" ]; then
	echo "error: '$ROOT' is not a directory" >&2
	exit 2
fi

# .godot/ is the import cache and holds copies of scenes; .git/ and build output
# are not authored by you either.
EXCLUDES="--exclude-dir=.godot --exclude-dir=.git --exclude-dir=bin --exclude-dir=obj"

# Optional allowlist for connections that legitimately target something this
# script cannot see - almost always a built-in engine method wired by hand, like
# `queue_free`. One method name per line, # for comments.
#
# This stays a project-local list on purpose. The alternative is a dictionary of
# Godot's own methods that would have to be re-synced with every engine release,
# to catch a case that comes up once or twice per project.
IGNORE_FILE="$ROOT/.signalignore"

is_ignored() {
	[ -f "$IGNORE_FILE" ] || return 1
	sed 's/#.*//' "$IGNORE_FILE" | tr -d ' \t' | grep -qx "$1"
}

if ! find "$ROOT" -name '*.tscn' -not -path '*/.godot/*' -not -path '*/.git/*' 2>/dev/null | grep -q .; then
	echo "no .tscn files under $ROOT - nothing to check"
	exit 0
fi

METHODS=$(mktemp)
trap 'rm -f "$METHODS"' EXIT INT TERM

# One connection per line - the format is generated by Godot and never wraps.
# shellcheck disable=SC2086
grep -rh '^\[connection' $EXCLUDES --include='*.tscn' "$ROOT" 2>/dev/null |
	sed -n 's/.*method="\([^"]*\)".*/\1/p' |
	sort -u >"$METHODS" || true

missing=0
checked=0
ignored=0

while IFS= read -r method; do
	[ -n "$method" ] || continue

	if is_ignored "$method"; then
		ignored=$((ignored + 1))
		continue
	fi

	checked=$((checked + 1))

	# A C# declaration or call site: `Name(`, not preceded by an identifier
	# character, so `OnPressed` does not match `NotOnPressed`.
	# shellcheck disable=SC2086
	if grep -rqE "(^|[^A-Za-z0-9_])${method}[[:space:]]*\(" $EXCLUDES --include='*.cs' "$ROOT" 2>/dev/null; then
		continue
	fi

	# GDScript, for mixed-language projects.
	# shellcheck disable=SC2086
	if grep -rqE "^[[:space:]]*func[[:space:]]+${method}[[:space:]]*\(" $EXCLUDES --include='*.gd' "$ROOT" 2>/dev/null; then
		continue
	fi

	if [ "$missing" -eq 0 ]; then
		echo "Signal connections pointing at methods that do not exist:"
		echo
	fi
	missing=$((missing + 1))

	# Show every scene that wires it, so the fix is one grep away.
	# shellcheck disable=SC2086
	grep -rn "method=\"${method}\"" $EXCLUDES --include='*.tscn' "$ROOT" 2>/dev/null |
		sed "s#^${ROOT}/##" |
		while IFS= read -r hit; do
			echo "  $hit"
		done
	echo
done <"$METHODS"

summary="$checked connection target(s) checked"
if [ "$ignored" -gt 0 ]; then
	summary="$summary, $ignored ignored via .signalignore"
fi

if [ "$missing" -gt 0 ]; then
	echo "$summary - $missing missing."
	echo
	echo "Either the handler was renamed or deleted, or the connection is stale."
	echo "Both fail at runtime, not at build time."
	echo "If a target is a built-in engine method, list it in .signalignore."
	exit 1
fi

echo "$summary - all resolve."
